# Generated by Django 5.1 on 2024-08-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_membership'),
    ]

    """ migrations.RenameField(
        model_name='membershipcard',
        old_name='user_type',
        new_name='membership_type',
    ),
    migrations.AlterField(
        model_name='membershipcard',
        name='profile_photo',
        field=models.ImageField(upload_to='profile_photos/'),
    ),
    """
    operations = [

    ]
