# Generated by Django 5.1 on 2024-08-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_type_membershipcard_membership_type_and_more'),
    ]

    operations = [       
    ]
