# Generated by Django 5.1 on 2024-08-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_membershipcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('membership_number', models.CharField(max_length=20, unique=True)),
                ('profile_photo', models.ImageField(upload_to='profile_photos/')),
                ('membership_type', models.CharField(choices=[('Standard', 'Standard'), ('Premium', 'Premium')], max_length=10)),
                ('benefits', models.TextField()),
            ],
        ),
    ]
